name: CI

on:
  push:
    # Build on tags that look like releases
    tags:
      - v*
    # Build when main or testing is pushed to
    branches:
      - main
      - testing
      - matlab_toolbox_actions # temporary
  pull_request:
    # Build when a pull request targets main
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  run-matlab-examples:
    name: Run the MATLAB examples
    runs-on: ubuntu-18.04
    timeout-minutes: 60
    env:
      PYTHON_VERSION: 3.8
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        matlab-version: ['R2020a', 'R2021a' ]
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set Up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ env.PYTHON_VERSION }}
          miniforge-version: latest
          activate-environment: matlab_test
      - name: Install Conda dependencies
        run: |
          conda install -q scons numpy ruamel.yaml cython boost-cpp fmt eigen yaml-cpp h5py pandas libgomp openblas pytest
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
          release: ${{ matrix.matlab-version }}
      - name: Build Cantera
        run: scons build env_vars=all -j2 debug=n matlab_path='/usr/local/MATLAB/${{ matrix.matlab-version }}/' --debug=time
      - name: Install Cantera
        # spot-check installation locations
        run: |
          scons install
      - name: Run MATLAB script
        uses: matlab-actions/run-command@v1
        with:
          command: pwd, cd('/usr/share/miniconda3/envs/matlab_test/share/cantera/matlab/'), pwd, addpath(genpath('MatlabToolbox')), path, cantera_root, LoadCantera, Air, Air.TPX

